version: "3.1"

networks:
  kong-network:
    driver: overlay

volumes:
  kong_db:
  kong_data:

services:
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    networks:
      - kong-network
    volumes:
      - kong_db:/var/lib/postgresql/data
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
        
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    networks:
      - kong-network
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
    depends_on:
      - kong-database
      
  kong:
     image: kong:latest
     environment:
       KONG_ADMIN_ACCESS_LOG: /dev/stdout
       KONG_ADMIN_ERROR_LOG: /dev/stderr
       KONG_ADMIN_LISTEN: '0.0.0.0:8001'
       KONG_DATABASE: postgres
       KONG_PG_DATABASE: kong
       KONG_PG_HOST: kong-database
       KONG_PG_USER: kong
       KONG_PROXY_ACCESS_LOG: /dev/stdout
       KONG_PROXY_ERROR_LOG: /dev/stderr
     networks:
       - kong-network
     ports:
       - "8888:8000/tcp"
       - "8001:8001/tcp"
       - "8443:8443/tcp"
       - "8444:8444/tcp"
     restart: on-failure
     healthcheck:
       test: ["CMD", "kong", "health"]
       interval: 10s
       timeout: 10s
       retries: 10
     depends_on:
       - kong-database
       - kong-migration

